// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raft.proto

package raft

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VoteRequest struct {
	Term                 uint32   `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateID          string   `protobuf:"bytes,2,opt,name=candidateID,proto3" json:"candidateID,omitempty"`
	LastLogIndex         uint32   `protobuf:"varint,3,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	LastLogTerm          uint32   `protobuf:"varint,4,opt,name=lastLogTerm,proto3" json:"lastLogTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteRequest) Reset()         { *m = VoteRequest{} }
func (m *VoteRequest) String() string { return proto.CompactTextString(m) }
func (*VoteRequest) ProtoMessage()    {}
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{0}
}

func (m *VoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteRequest.Unmarshal(m, b)
}
func (m *VoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteRequest.Marshal(b, m, deterministic)
}
func (m *VoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteRequest.Merge(m, src)
}
func (m *VoteRequest) XXX_Size() int {
	return xxx_messageInfo_VoteRequest.Size(m)
}
func (m *VoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VoteRequest proto.InternalMessageInfo

func (m *VoteRequest) GetTerm() uint32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *VoteRequest) GetCandidateID() string {
	if m != nil {
		return m.CandidateID
	}
	return ""
}

func (m *VoteRequest) GetLastLogIndex() uint32 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *VoteRequest) GetLastLogTerm() uint32 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

type VoteResponse struct {
	Term                 uint32   `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted          bool     `protobuf:"varint,2,opt,name=voteGranted,proto3" json:"voteGranted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteResponse) Reset()         { *m = VoteResponse{} }
func (m *VoteResponse) String() string { return proto.CompactTextString(m) }
func (*VoteResponse) ProtoMessage()    {}
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{1}
}

func (m *VoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteResponse.Unmarshal(m, b)
}
func (m *VoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteResponse.Marshal(b, m, deterministic)
}
func (m *VoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteResponse.Merge(m, src)
}
func (m *VoteResponse) XXX_Size() int {
	return xxx_messageInfo_VoteResponse.Size(m)
}
func (m *VoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VoteResponse proto.InternalMessageInfo

func (m *VoteResponse) GetTerm() uint32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *VoteResponse) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

type EntryData struct {
	Term                 uint32   `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderID             string   `protobuf:"bytes,2,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
	PrevLogIndex         uint32   `protobuf:"varint,3,opt,name=prevLogIndex,proto3" json:"prevLogIndex,omitempty"`
	PrevLogTerm          uint32   `protobuf:"varint,4,opt,name=prevLogTerm,proto3" json:"prevLogTerm,omitempty"`
	Entries              []*Entry `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit         uint32   `protobuf:"varint,6,opt,name=leaderCommit,proto3" json:"leaderCommit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryData) Reset()         { *m = EntryData{} }
func (m *EntryData) String() string { return proto.CompactTextString(m) }
func (*EntryData) ProtoMessage()    {}
func (*EntryData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{2}
}

func (m *EntryData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryData.Unmarshal(m, b)
}
func (m *EntryData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryData.Marshal(b, m, deterministic)
}
func (m *EntryData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryData.Merge(m, src)
}
func (m *EntryData) XXX_Size() int {
	return xxx_messageInfo_EntryData.Size(m)
}
func (m *EntryData) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryData.DiscardUnknown(m)
}

var xxx_messageInfo_EntryData proto.InternalMessageInfo

func (m *EntryData) GetTerm() uint32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *EntryData) GetLeaderID() string {
	if m != nil {
		return m.LeaderID
	}
	return ""
}

func (m *EntryData) GetPrevLogIndex() uint32 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *EntryData) GetPrevLogTerm() uint32 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *EntryData) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *EntryData) GetLeaderCommit() uint32 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

type EntryResults struct {
	Term                 uint32   `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryResults) Reset()         { *m = EntryResults{} }
func (m *EntryResults) String() string { return proto.CompactTextString(m) }
func (*EntryResults) ProtoMessage()    {}
func (*EntryResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{3}
}

func (m *EntryResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryResults.Unmarshal(m, b)
}
func (m *EntryResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryResults.Marshal(b, m, deterministic)
}
func (m *EntryResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryResults.Merge(m, src)
}
func (m *EntryResults) XXX_Size() int {
	return xxx_messageInfo_EntryResults.Size(m)
}
func (m *EntryResults) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryResults.DiscardUnknown(m)
}

var xxx_messageInfo_EntryResults proto.InternalMessageInfo

func (m *EntryResults) GetTerm() uint32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *EntryResults) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Entry struct {
	Term                 uint32   `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{4}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetTerm() uint32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Entry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*VoteRequest)(nil), "VoteRequest")
	proto.RegisterType((*VoteResponse)(nil), "VoteResponse")
	proto.RegisterType((*EntryData)(nil), "EntryData")
	proto.RegisterType((*EntryResults)(nil), "EntryResults")
	proto.RegisterType((*Entry)(nil), "Entry")
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor_b042552c306ae59b) }

var fileDescriptor_b042552c306ae59b = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x3f, 0x6b, 0xf3, 0x30,
	0x10, 0xc6, 0xe3, 0x37, 0xff, 0xcf, 0xf6, 0x22, 0xde, 0xc1, 0x64, 0x32, 0x9a, 0x32, 0x04, 0x43,
	0xd3, 0xb5, 0x4b, 0x69, 0x42, 0x09, 0x94, 0x0e, 0xa6, 0x74, 0x57, 0xa3, 0x4b, 0x09, 0x38, 0x92,
	0x2b, 0x9d, 0x43, 0xfb, 0x11, 0xfa, 0xc9, 0xfa, 0xb5, 0x8a, 0x15, 0x25, 0xa8, 0xc5, 0xdd, 0xfc,
	0x3c, 0xf8, 0x74, 0xcf, 0xef, 0xee, 0x00, 0x8c, 0xd8, 0x51, 0x51, 0x1b, 0x4d, 0x9a, 0x7f, 0x46,
	0x10, 0x3f, 0x6b, 0xc2, 0x12, 0xdf, 0x1a, 0xb4, 0xc4, 0x18, 0x0c, 0x08, 0xcd, 0x21, 0x8b, 0xf2,
	0x68, 0x9e, 0x96, 0xee, 0x9b, 0xe5, 0x10, 0x6f, 0x85, 0x92, 0x7b, 0x29, 0x08, 0x37, 0xab, 0xec,
	0x5f, 0x1e, 0xcd, 0xa7, 0x65, 0x68, 0x31, 0x0e, 0x49, 0x25, 0x2c, 0x3d, 0xe8, 0xd7, 0x8d, 0x92,
	0xf8, 0x9e, 0xf5, 0x5d, 0xf5, 0x0f, 0xaf, 0x7d, 0xc5, 0xeb, 0xa7, 0xb6, 0xc1, 0xc0, 0xfd, 0x12,
	0x5a, 0x7c, 0x05, 0xc9, 0x29, 0x8a, 0xad, 0xb5, 0xb2, 0xf8, 0x57, 0x96, 0xa3, 0x26, 0xbc, 0x37,
	0x42, 0x11, 0x4a, 0x97, 0x65, 0x52, 0x86, 0x16, 0xff, 0x8a, 0x60, 0xba, 0x56, 0x64, 0x3e, 0x56,
	0x82, 0x44, 0xe7, 0x1b, 0x33, 0x98, 0x54, 0x28, 0x24, 0x9a, 0x0b, 0xcc, 0x45, 0xb7, 0x24, 0xb5,
	0xc1, 0xe3, 0x6f, 0x92, 0xd0, 0x6b, 0x33, 0x78, 0x1d, 0x92, 0x04, 0x16, 0xcb, 0x61, 0x8c, 0x8a,
	0xcc, 0x1e, 0x6d, 0x36, 0xcc, 0xfb, 0xf3, 0x78, 0x39, 0x2a, 0x5c, 0xa4, 0xf2, 0x6c, 0xbb, 0x89,
	0xb9, 0x9e, 0x77, 0xfa, 0x70, 0xd8, 0x53, 0x36, 0xf2, 0x13, 0x0b, 0x3c, 0x7e, 0x03, 0xc9, 0xa9,
	0x0a, 0x6d, 0x53, 0x91, 0xed, 0x64, 0xc9, 0x60, 0x6c, 0x9b, 0xed, 0x16, 0xad, 0xf5, 0xb3, 0x38,
	0x4b, 0x7e, 0x05, 0x43, 0x57, 0xdd, 0x59, 0xf6, 0x1f, 0x86, 0x47, 0x51, 0x35, 0xe8, 0xf9, 0x4f,
	0x62, 0xb9, 0x83, 0x49, 0x29, 0x76, 0xf4, 0xa8, 0x25, 0xb2, 0x05, 0xc4, 0xfe, 0x26, 0xda, 0x9d,
	0xb0, 0xa4, 0x08, 0xae, 0x64, 0x96, 0x16, 0xe1, 0xa2, 0x78, 0x8f, 0x2d, 0x20, 0xbd, 0xad, 0x6b,
	0x54, 0x72, 0xed, 0xf9, 0xa0, 0xb8, 0xec, 0x60, 0x96, 0x16, 0x21, 0x06, 0xef, 0xbd, 0x8c, 0xdc,
	0xed, 0x5d, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xc3, 0xbc, 0x10, 0x89, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RaftNodeClient is the client API for RaftNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftNodeClient interface {
	RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
	AppendEntries(ctx context.Context, in *EntryData, opts ...grpc.CallOption) (*EntryResults, error)
}

type raftNodeClient struct {
	cc *grpc.ClientConn
}

func NewRaftNodeClient(cc *grpc.ClientConn) RaftNodeClient {
	return &raftNodeClient{cc}
}

func (c *raftNodeClient) RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	out := new(VoteResponse)
	err := c.cc.Invoke(ctx, "/RaftNode/RequestVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftNodeClient) AppendEntries(ctx context.Context, in *EntryData, opts ...grpc.CallOption) (*EntryResults, error) {
	out := new(EntryResults)
	err := c.cc.Invoke(ctx, "/RaftNode/AppendEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftNodeServer is the server API for RaftNode service.
type RaftNodeServer interface {
	RequestVote(context.Context, *VoteRequest) (*VoteResponse, error)
	AppendEntries(context.Context, *EntryData) (*EntryResults, error)
}

// UnimplementedRaftNodeServer can be embedded to have forward compatible implementations.
type UnimplementedRaftNodeServer struct {
}

func (*UnimplementedRaftNodeServer) RequestVote(ctx context.Context, req *VoteRequest) (*VoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVote not implemented")
}
func (*UnimplementedRaftNodeServer) AppendEntries(ctx context.Context, req *EntryData) (*EntryResults, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendEntries not implemented")
}

func RegisterRaftNodeServer(s *grpc.Server, srv RaftNodeServer) {
	s.RegisterService(&_RaftNode_serviceDesc, srv)
}

func _RaftNode_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftNodeServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RaftNode/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftNodeServer).RequestVote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftNode_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntryData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftNodeServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RaftNode/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftNodeServer).AppendEntries(ctx, req.(*EntryData))
	}
	return interceptor(ctx, in, info, handler)
}

var _RaftNode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RaftNode",
	HandlerType: (*RaftNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVote",
			Handler:    _RaftNode_RequestVote_Handler,
		},
		{
			MethodName: "AppendEntries",
			Handler:    _RaftNode_AppendEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}
